name: CI Tests

# Triggered on push or pull request events (master branch)
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run all unit tests
        run: deno test --allow-run --allow-write=./tests --allow-read=./tests ./tests
